qec:
  d: 7
  rounds: 7
  basis: Z
  data_qubit_error_rate: 0.01
  meas_error_rate: 0.01

data:
  raw_sample_shots: 150000
  split_ratio: 0.8
  remove_trivial_syndrome_shots: true
  remove_bp_easy_shots: false

seed: 42
