[project]
name = "pytorch-decoders"
version = "0.1.0"
description = "Neural-network-based QEC decoders."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "qecdec",
    "torchdecoder_core",
    "numpy",
    "torch",
    "lightning",
    "tensorboard",
    "torch-tb-profiler",
    "omegaconf",
    "tabulate",
    "humanize",
    "stim",
    "tqdm",
]

[tool.uv]
package = false

[tool.uv.sources]
qecdec = { workspace = true }
torchdecoder_core = { workspace = true }
