"""
Python script to test a trained PyTorch decoder.

Usage:
    uv run python test.py --run-dir <path/to/run_directory>

Example: (from the torchdecoder/scripts directory)
    uv run python test.py --run-dir ../runs/RotatedSurfaceCode_Phenomenological/d=5_rounds=5_basis=Z/MultiDMemBP/run_0

The run directory must contain config.yaml and checkpoints/best_model.ckpt (which was saved during training).
"""

import argparse
import os
from pathlib import Path
import warnings

from omegaconf import OmegaConf, DictConfig
import lightning as L
from qecdec.experiments import RotatedSurfaceCode_Memory

from lightning_utils import DecodingDataModule, DecodingModule

DATASETS_ROOT = Path(__file__).resolve().parent.parent / "datasets"


def load_config(path: Path) -> DictConfig:
    if not path.exists():
        raise FileNotFoundError(f"Config file not found: {path}")
    cfg = OmegaConf.load(path)
    OmegaConf.resolve(cfg)
    OmegaConf.set_struct(cfg, True)  # forbid creation of new keys
    if cfg.data.num_workers is None:
        cfg.data.num_workers = max(1, (os.cpu_count() or 1) - 1)
    OmegaConf.set_readonly(cfg, True)  # forbid modification from now on
    return cfg


def get_data_dir(qec_cfg) -> Path:
    code = qec_cfg.code
    noise_model = qec_cfg.noise_model
    d = qec_cfg.d
    rounds = qec_cfg.rounds
    basis = qec_cfg.basis
    return DATASETS_ROOT.joinpath(
        f"{code}_{noise_model}",
        f"d={d}_rounds={rounds}_basis={basis}",
    )


def main():
    parser = argparse.ArgumentParser(description="Test a trained PyTorch decoder")
    parser.add_argument(
        "--run-dir", required=True, type=str, help="Path to run directory"
    )
    args = parser.parse_args()

    run_dir = Path(args.run_dir).resolve()
    if not run_dir.exists():
        raise FileNotFoundError(f"Run directory not found: {run_dir}")
    ckpt_path = run_dir / "checkpoints" / "best_model.ckpt"
    if not ckpt_path.exists():
        raise FileNotFoundError(f"Checkpoint not found: {ckpt_path}")
    config_path = run_dir / "config.yaml"
    cfg = load_config(config_path)
    qec_cfg = cfg.qec
    data_dir = get_data_dir(cfg.qec)
    print(f">>>>>> Run directory: {run_dir}")
    print(f">>>>>> Data directory: {data_dir}")
    print(f">>>>>> Checkpoint path: {ckpt_path}")

    if (
        qec_cfg.code == "RotatedSurfaceCode"
        and qec_cfg.noise_model == "Phenomenological"
    ):
        expmt = RotatedSurfaceCode_Memory(
            d=qec_cfg.d,
            rounds=qec_cfg.rounds,
            basis=qec_cfg.basis,
            data_qubit_error_rate=qec_cfg.p,
            meas_error_rate=qec_cfg.p,
        )
    else:
        raise ValueError(
            f"Unsupported combination: {qec_cfg.code} + {qec_cfg.noise_model}"
        )
    decoder = DecodingModule.load_from_checkpoint(
        str(ckpt_path),
        weights_only=False,
        chkmat=expmt.chkmat,
        obsmat=expmt.obsmat,
        prior=expmt.prior,
        model_cfg=cfg.model,
        loss_cfg=cfg.loss,
        optim_cfg=cfg.optim,
        compile_mode=cfg.compile_mode,
    )

    datamodule = DecodingDataModule(
        data_dir,
        batch_size=cfg.data.batch_size,
        num_workers=cfg.data.num_workers,
    )

    trainer = L.Trainer(
        accelerator=cfg.trainer.accelerator,
        enable_progress_bar=cfg.trainer.enable_progress_bar,
    )

    # Start testing
    trainer.test(model=decoder, datamodule=datamodule, verbose=False)


if __name__ == "__main__":
    # Filter out some warnings generated by lightning package.
    warnings.filterwarnings(
        "ignore",
        category=FutureWarning,
        message="`isinstance\\(treespec, LeafSpec\\)` is deprecated",
    )

    # torch.set_float32_matmul_precision("high")

    main()
