qec:
  code: BB_144_12_12
  noise_model: CircuitLevel
  d: 12
  rounds: 12
  basis: X
  p_range: [0.003, 0.004, 0.005]
  load_circuit_from_file: true

data:
  train_size: 100000
  val_size: 10000
  test_size: 10000
  max_easy_sample_ratio: 0.5
  # membp_max_iter and membp_gamma are used to classify hard vs easy shots
  membp_max_iter: 50
  membp_gamma: 0.2
