qec:
  code: RotatedSurfaceCode
  noise_model: Phenomenological
  d: 9
  rounds: 9
  basis: Z
  p_range: [0.008, 0.01, 0.015, 0.02]
  load_circuit_from_file: false

data:
  train_size: 100000
  val_size: 10000
  test_size: 10000
  max_easy_sample_ratio: 0.5
  # membp_max_iter and membp_gamma are used to classify hard vs easy shots
  membp_max_iter: 10
  membp_gamma: 0.0
