qec:
  code: RotatedSurfaceCode
  noise_model: Phenomenological
  d: 5
  rounds: 5
  basis: Z
  p: 0.01

model:
  name: MultiDMemBP
  num_iters: 5
  msg_features: 16
  min_impl_method: smooth
  sign_impl_method: smooth
  gamma_shared: true  # true = one gamma per VN, shared across message components; false = one gamma per VN and per message component
  gamma_init: 0  # single scalar: all gamma use this value; [a, b]: sample independently and uniformly from [a, b]
  mlp:
    hidden_features: 64
    hidden_depth: 2
    activation: Tanh  # options: "Sigmoid", "Tanh", "ReLU", "GELU", "SiLU".
    norm: null  # null = no normalization; options: "LayerNorm", "RMSNorm".
    dropout_p: 0.05

loss:
  beta: 0.8
  skip_iters: 0

optim:
  lr: 0.002
  lr_scheduler:
    factor: 0.2
    patience: 3
    threshold: 0.001
    threshold_mode: abs

early_stopping:
  min_delta: 0.0001
  patience: 5

tb_logger:
  log_graph: false

data:
  batch_size: 256
  num_workers: null   # null = use os.cpu_count() at runtime

trainer:
  accelerator: auto  # auto = auto-detect available accelerator
  max_epochs: 50
  enable_progress_bar: true
